### ISSUE TITLE
Mod source code license?

### ISSUE THREAD

**Issue by jibsaram** [Armitxes/StardewValley_UnlimitedPlayers#10]
Hi there! I'm looking at your mod and possibly using it and contributing to its code, but it currently has no license specified. Could you let me know (and, ideally, update your repo) what license you'd like to release your source code under?

Many thanks!

**Comment by Armitxes** [comment]
@hellodeibu 

Sorry for the wait. It's licensed under the GNU GPL v3.0
Everyone who wants to work on the project is more than welcome and will be given credits & required rights respectively.
